artifact_location: /Users/ajayyy/Desktop/Deep_Learning/Smart-Quality-Inspection-System/runs/mlflow/162470455450907832
creation_time: 1761595533497
experiment_id: '162470455450907832'
last_update_time: 1761595533497
lifecycle_stage: active
name: /Shared/Ultralytics
