artifact_location: /Users/ajayyy/Desktop/Deep_Learning/Smart-Quality-Inspection-System/runs/mlflow/0
creation_time: 1761595533491
experiment_id: '0'
last_update_time: 1761595533491
lifecycle_stage: active
name: Default
